repos:
  - repo: local
    hooks:
      - id: make-check
        name: Run all checks via make
        entry: make check
        language: system
        pass_filenames: false
        always_run: true